### ISSUE TITLE
Dont redirected bf2

### ISSUE THREAD

**Issue by Adalbertus250** [BF2Statistics/BF2GamespyRedirector#1]
Hello, I need help, your application does not want to redirected battlefield 2 to my server
writes this when I run it: battlefield 2 is running any modification woll not take effect until battlefield 2 is restarted. and that's what I'm just running through.

**Comment by tmiland** [comment]
Hi, have you tried running the application as admin?

**Comment by killergames156** [comment]
yes the application was running in the administrator

**Comment by wilson212** [comment]
Sorry for the late reply. What redirect mode are you using?
